### ISSUE TITLE
search string generates fault

### ISSUE THREAD

**Issue by wujastyk** [sarit/sarit-existdb#1]
The error below is produced by trying the search string

- sendriya[. ]\*cetan.\*

------

<?xml version="1.0" ?><exception><path>/db/apps/sarit-pm/modules/view.xql</path><message>exerr:ERROR Syntax error in Lucene query string: Cannot parse 'sendriya[. ]*cetan.*': Encountered " "]" "] "" at line 1, column 11.
Was expecting one of:
    "TO" ...
    <RANGE_QUOTED> ...
    <RANGE_GOOP> ...
     [at line 542, column 25]
In function:
	app:query(node()*, map, xs:string?, xs:string+, xs:string, xs:string+, xs:string+, xs:string) [229:18:/db/apps/sarit-pm/modules/app.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call(item(), element(), map) [143:37:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [146:81:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [524:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	pages:app-root(node(), map) [217:18:/db/apps/sarit-pm/modules/lib/pages.xql]
	templates:call-with-args(function, function*, element(), map) [208:13:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [465:17:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process-output(element(), map, item()*) [273:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process-output(element(), map, item()*, element()) [205:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call-by-introspection(element(), map, map, function) [187:28:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:call(item(), element(), map) [135:36:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [131:51:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:process(node()*, map) [88:9:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]
	templates:apply(node()+, function, map?, map?) [48:5:/opt/lib/sarit-existdb/exist/webapp/WEB-INF/data/expathrepo/shared-0.4.2/content/templates.xql]</message></exception>

**Comment by paddymcall** [comment]
Thanks for spotting this.  What's the expected result here?

**Comment by wujastyk** [comment]
My search string was faulty - I was trying to do a regexp search for two
words without suffixes but possibly separated by a space.  But even if
faulty, it shouldn't break the system.

Best,
Dominik

**Comment by paddymcall** [comment]
Unfortunately, it's currently not able to fix this in sarit's exist-db instance.  It would need some work on the lucene query parser module that belongs to the standard exist-db distribution.  The current behaviour of the SARIT web-app is not very elegant, but technically correct.

**Comment by wujastyk** [comment]
👍
